In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xgboost
import sklearn

I have decided to work on the hourly dataset :

In [2]:
df=pd.read_csv('/home/yazid/sklearn/bikes/data/hour.csv')

In [3]:
df.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [4]:
len(df)

17379

In [5]:
df.drop('instant',axis=1,inplace=True)

In [6]:
df['dteday']=pd.to_datetime(df['dteday'])

Let's create some features :

Cyclical temporical features :

In [7]:
df['hr_sin']=np.sin(2*np.pi*(df['hr']/24))
df['hr_cos']=np.cos(2*np.pi*(df['hr']/24))
df['mnth_sin']=np.sin(2*np.pi*(df['mnth']/12))
df['mnth_cos']=np.cos(2*np.pi*(df['mnth']/12))
df['week_sin']=np.sin(2*np.pi*(df['weekday']/7))
df['week_cos']=np.cos(2*np.pi*(df['weekday']/7))

Commute features :

In [8]:
df['Rush_Hour']=((df['workingday']==1)&(df['hr'].isin([7,8,9,17,18,19]))).astype(bool)
df['Off_Peak']=(df['hr'].isin([0,1,2,3,4,5])).astype(bool)

In [9]:
df['Previous_hour_cnt']=df['cnt'].shift(1)
df['Previous_day_cnt']=df['cnt'].shift(24)

We create now weather based columns :

In [10]:
df['delta_temp']=df['temp']-df['atemp']
df['temp*hum']=df['temp']*df['hum']
df['bad_weather']=(df['weathersit']>=3).astype(bool)
df['windspeed*temp']=(df['temp']*df['windspeed'])

Let's create rolling averages feature:

In [11]:
df['cnt_roll_3h_mean']=(df['cnt'].shift(1).rolling(window=3).mean())
df['cnt_roll_3h_std']=(df['cnt'].shift(1).rolling(window=3).std())
df['cnt_roll_24_std']=(df['cnt'].shift(1).rolling(window=24).std())

In [12]:
#We log transform target since it is righly skewed:
df['log_cnt']=np.log1p(df['cnt'])
df.drop('cnt',axis=1,inplace=True)

Let's create function to extract feature_importance:

In [13]:
def feature_importance(model):
    feature_names=model.feature_names_in_
    return pd.DataFrame({'Feature':feature_names,
                        'Importance':model.feature_importances_}).sort_values('Importance',ascending=False).reset_index(drop=True)

In [14]:
df.dropna(inplace=True)

In [15]:
#This will be used later for train_test_split:
len(df)*0.8

13884.0

In [16]:
X=df.drop(['log_cnt','casual','registered','dteday'],axis=1)
y=df['log_cnt']
X_train=X[:13768]
X_test=X[13768:]
y_train=y[:13768]
y_test=y[13768:]

In [17]:
from sklearn.ensemble import RandomForestRegressor
v0=RandomForestRegressor()
v0.fit(X_train,y_train)

RandomForestRegressor()

In [18]:
from sklearn.metrics import mean_absolute_error
y_pred_0=v0.predict(X_test)
mae_0=mean_absolute_error(y_test,y_pred_0 )
(mae_0 /y_test.median())*100

np.float64(3.4096302115136377)

Our first model is performing well let's try to improve things further with RandomizedSearchCV

In [19]:
'''
# I ran this on colab gpu and got results i wanted:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV,TimeSeriesSplit


tscv=TimeSeriesSplit(n_splits=5)
xgb_model = XGBRegressor(
    tree_method="hist",
    device="cuda",
    random_state=42
)

xgb_grid = {
    'n_estimators': [100, 300, 500],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [6, 8, 10,12],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree':[0.6,0.8,1.0],
    'gamma':[0,0.1,0.2]
}

randomized_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=xgb_grid,
    n_iter=40,
    cv=tscv,
    scoring='neg_root_mean_squared_error',
    random_state=42,
    verbose=1
)

randomized_search.fit(X_train, y_train)
'''

'\n# I ran this on colab gpu and got results i wanted:\nfrom xgboost import XGBRegressor\nfrom sklearn.model_selection import RandomizedSearchCV,TimeSeriesSplit\n\n\ntscv=TimeSeriesSplit(n_splits=5)\nxgb_model = XGBRegressor(\n    tree_method="hist",\n    device="cuda",\n    random_state=42\n)\n\nxgb_grid = {\n    \'n_estimators\': [100, 300, 500],\n    \'learning_rate\': [0.01, 0.05, 0.1],\n    \'max_depth\': [6, 8, 10,12],\n    \'subsample\': [0.6, 0.8, 1.0],\n    \'colsample_bytree\':[0.6,0.8,1.0],\n    \'gamma\':[0,0.1,0.2]\n}\n\nrandomized_search = RandomizedSearchCV(\n    estimator=xgb_model,\n    param_distributions=xgb_grid,\n    n_iter=40,\n    cv=tscv,\n    scoring=\'neg_root_mean_squared_error\',\n    random_state=42,\n    verbose=1\n)\n\nrandomized_search.fit(X_train, y_train)\n'

In [20]:
'''
Here are results from colab_gpu:
print(randomized_search.best_params_)
#{'subsample': 0.8, 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 1.0}
'''

"\nHere are results from colab_gpu:\nprint(randomized_search.best_params_)\n#{'subsample': 0.8, 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 1.0}\n"

In [21]:
from xgboost import XGBRegressor
v1=XGBRegressor(n_esimators=500,subsample=0.8,max_depth=6,learning_rate=0.05,gamma=0.1,colsample_bytree=1.0,random_state=42,tree_method='hist',n_jobs=-1)
v1.fit(X_train,y_train)

/home/yazid/sklearn/.venv/lib64/python3.14/site-packages/xgboost/training.py:200: UserWarning: [17:52:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "n_esimators" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_esimators=500,
             n_estimators=None, n_jobs=-1, ...)

In [22]:
from sklearn.metrics import root_mean_squared_error
y_pred_1=v1.predict(X_test)
rmse_1=root_mean_squared_error(np.expm1(y_test),np.expm1(y_pred_1))
rmse_1

56.50721604223677

In [23]:
feature_importance(v1)

              Feature  Importance
0   Previous_hour_cnt    0.635666
1                  hr    0.120335
2              hr_cos    0.046271
3    Previous_day_cnt    0.036559
4          workingday    0.024858
5           Rush_Hour    0.018594
6     cnt_roll_24_std    0.012175
7    cnt_roll_3h_mean    0.009132
8            week_cos    0.008594
9                temp    0.008176
10         weathersit    0.008160
11               mnth    0.007791
12             hr_sin    0.007727
13           week_sin    0.006594
14             season    0.005616
15    cnt_roll_3h_std    0.005345
16                 yr    0.004865
17            weekday    0.004713
18              atemp    0.004401
19            holiday    0.004117
20           mnth_cos    0.003968
21           temp*hum    0.003037
22     windspeed*temp    0.003033
23                hum    0.002918
24           mnth_sin    0.002551
25          windspeed    0.002496
26         delta_temp    0.002311
27           Off_Peak    0.000000
28        bad_weather    0.000000

We drop features with no predictive value :They just introduced noise:

In [24]:
df.drop(['bad_weather','Off_Peak'],axis=1,inplace=True)

In [32]:
X=df.drop(['log_cnt','dteday','casual','registered'],axis=1)
y=df['log_cnt']
X_train=X[:13884]
X_test=X[13884:]
y_train=y[:13884]
y_test=y[13884:]

In [33]:
v2=XGBRegressor(n_esimators=300,subsample=0.8,max_depth=6,learning_rate=0.05,gamma=0.1,colsample_bytree=1.0,random_state=42,tree_method='hist',n_jobs=-1)
v2.fit(X_train,y_train)

/home/yazid/sklearn/.venv/lib64/python3.14/site-packages/xgboost/training.py:200: UserWarning: [18:03:13] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "n_esimators" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.1, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_esimators=300,
             n_estimators=None, n_jobs=-1, ...)

In [34]:
y_pred_2=v2.predict(X_test)
rmse_2=root_mean_squared_error(np.expm1(y_test),np.expm1(y_pred_2))
rmse_2

55.69565242716538

In [35]:
feature_importance(v2)

              Feature  Importance
0   Previous_hour_cnt    0.635853
1                  hr    0.121255
2              hr_cos    0.046261
3    Previous_day_cnt    0.037806
4          workingday    0.024381
5           Rush_Hour    0.017218
6     cnt_roll_24_std    0.012733
7    cnt_roll_3h_mean    0.008642
8          weathersit    0.008230
9              hr_sin    0.007969
10           week_cos    0.007967
11               mnth    0.007822
12               temp    0.007503
13           week_sin    0.007222
14             season    0.005555
15              atemp    0.005260
16                 yr    0.005089
17    cnt_roll_3h_std    0.004970
18            weekday    0.004664
19           mnth_cos    0.003980
20           temp*hum    0.003315
21            holiday    0.003268
22     windspeed*temp    0.002784
23                hum    0.002741
24           mnth_sin    0.002661
25          windspeed    0.002439
26         delta_temp    0.002413